export const PROJECTS = [
  {
    name: 'pablosirera.com',
    description: 'projects.portfolio',
    language: 'Vue',
    stars: 2,
    forks: 1,
    url: 'https://github.com/pablosirera/pablosirera.com',
  },
  {
    name: 'timeline-vuejs',
    description: 'projects.timeline',
    language: 'Vue',
    stars: 64,
    forks: 13,
    url: 'https://github.com/pablosirera/timeline-vuejs',
  },
  {
    name: 'tracking-plants',
    description: 'projects.trackingPlants',
    language: 'JavaScript',
    stars: 2,
    forks: 0,
    url: 'https://github.com/pablosirera/tracking-plants',
  },
  {
    name: 'github-ranking',
    description: 'projects.githubRanking',
    stars: 5,
    forks: 0,
    url: 'https://github.com/pablosirera/github-ranking',
  },
  {
    name: 'nearest-bin',
    description: 'projects.nearestBin',
    language: 'Vue',
    stars: 0,
    forks: 0,
    url: 'https://github.com/pablosirera/nearest-bin',
  },
  {
    name: 'who-reviews',
    description: 'projects.whoReviews',
    language: 'JavaScript',
    stars: 0,
    forks: 0,
    url: 'https://github.com/pablosirera/who-reviews',
  },
]
